spring:
  application:
    name:  golf-office-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/golf_api?useTimezone=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    properties:
      hibernate:
    show-sql: ${JPA_SHOW_SQL:false}
    open-in-view: false

security:
  jwt:
    secret: ${JWT_SECRET:change-this-secret-key-before-production-change-this-secret-key}
    access-token-expiration-minutes: ${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES:15}
    refresh-token-expiration-hours: ${JWT_REFRESH_TOKEN_EXPIRATION_HOURS:12}
